<?php

namespace App\ContentManagementBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContentBlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentBlockRepository extends EntityRepository
{

}
