<?php

namespace App\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleRepository extends EntityRepository
{
    public function findUnAssigned($list)
    {
        $em = $this->getEntityManager();
        $dql = "SELECT m FROM AdminBundle:Module m WHERE m NOT IN (:list)";
        $query = $em->createQuery($dql);
        $query->setParameter('list', $list);
        return $query->getResult();
    }
}
