<?php

namespace Proxies\__CG__\App\AdminBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Content extends \App\AdminBundle\Entity\Content implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'App\\AdminBundle\\Entity\\Content' . "\0" . 'id', '' . "\0" . 'App\\AdminBundle\\Entity\\Content' . "\0" . 'productsLimitPrice', '' . "\0" . 'App\\AdminBundle\\Entity\\Content' . "\0" . 'cantByProductType', '' . "\0" . 'App\\AdminBundle\\Entity\\Content' . "\0" . 'module', '' . "\0" . 'App\\AdminBundle\\Entity\\Content' . "\0" . 'productsType');
        }

        return array('__isInitialized__', '' . "\0" . 'App\\AdminBundle\\Entity\\Content' . "\0" . 'id', '' . "\0" . 'App\\AdminBundle\\Entity\\Content' . "\0" . 'productsLimitPrice', '' . "\0" . 'App\\AdminBundle\\Entity\\Content' . "\0" . 'cantByProductType', '' . "\0" . 'App\\AdminBundle\\Entity\\Content' . "\0" . 'module', '' . "\0" . 'App\\AdminBundle\\Entity\\Content' . "\0" . 'productsType');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Content $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductsLimitPrice($productsLimitPrice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductsLimitPrice', array($productsLimitPrice));

        return parent::setProductsLimitPrice($productsLimitPrice);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductsLimitPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductsLimitPrice', array());

        return parent::getProductsLimitPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setCantByProductType($cantByProductType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCantByProductType', array($cantByProductType));

        return parent::setCantByProductType($cantByProductType);
    }

    /**
     * {@inheritDoc}
     */
    public function getCantByProductType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCantByProductType', array());

        return parent::getCantByProductType();
    }

    /**
     * {@inheritDoc}
     */
    public function setModule(\App\AdminBundle\Entity\Module $module)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModule', array($module));

        return parent::setModule($module);
    }

    /**
     * {@inheritDoc}
     */
    public function getModule()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModule', array());

        return parent::getModule();
    }

    /**
     * {@inheritDoc}
     */
    public function addProductsType(\App\AdminBundle\Entity\ProductType $productsType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProductsType', array($productsType));

        return parent::addProductsType($productsType);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProductsType(\App\AdminBundle\Entity\ProductType $productsType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProductsType', array($productsType));

        return parent::removeProductsType($productsType);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductsType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductsType', array());

        return parent::getProductsType();
    }

}
