security:
    encoders:
        App\AdminBundle\Entity\User:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_FREE: ROLE_FREE
        ROLE_PAYMENT: ROLE_PAYMENT
        ROLE_ADMIN: [ROLE_FREE, ROLE_PAYMENT, ROLE_ALLOWED_TO_SWITCH]

    providers:
            main:
                entity: { class: App\AdminBundle\Entity\User, property: username }


    firewalls:
        
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        secured_area:
            pattern:    ^/*
            form_login:
                #success_handler: authentication_handler
                #failure_handler: authentication_handler
                check_path: /check
                login_path: /login
                username_parameter: _username
                password_parameter: _password
                always_use_default_target_path: true
                default_target_path: /backoffice
            logout:
                #success_handler: logout_handler
                path:   /logout
                target: /login
            #http_basic:
            #    realm: "Secured Demo Area"
            anonymous: ~

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/homepage, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/join, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/contact, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/about, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/product, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/products/type, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backoffice/^, roles: [ROLE_FREE, ROLE_PAYMENT, ROLE_ADMIN] }
        - { path: ^/backoffice/config/^, allow_if: 'has_role("ROLE_ADMIN")' }